Enhance UNICODE support
GameTechDev/PresentMon pull request #192
Opened 2023-12-12 12:18 UTC by malikm

Also to fix #191

2023-12-12 17:28 UTC, JeffersonMontgomery-Intel requested changes
Thank-you for the contribution!

There is one change that is needed (see inline comment).  I probably would have gone with wchar_t vs WCHAR, but don't bother changing that now.

I will pull, test, and accept this sometime this week.  I can fix that one event then so you don't need to, this is just FYI.

2023-12-12 17:28 UTC, JeffersonMontgomery-Intel commented on PresentData/PresentMonTraceConsumer.cpp
>              event.IsStartEvent  = true;
AFAIK the underlying data for this event is always char, and GetData<T>() doesn't do any conversion, it just accesses the event data as if it were a T.  So, we need to leave it as GetData<string>() and then convert here.

In debug build GetData() should be asserting with this change, though you'll only hit this event when processing from an ETL file (--etl_file).

2023-12-12 21:42 UTC, malikm commented
Thanks for the review. I did all changes requested, hope it's OK now :)

2023-12-14 20:43 UTC, JeffersonMontgomery-Intel commented
Thanks!  Testing now and everything looks good.  I plumbed it through to the CSV too so should be supported throughout now:

<img width="949" alt="image" src="https://github.com/GameTechDev/PresentMon/assets/33905536/7abb36f3-8bb8-447e-b9b9-b512a4f910bf">

Should land in main branch today or tomorrow.

2023-12-28 18:17 UTC, closed without merging